### ISSUE TITLE
Button click won't fire the right event

### ISSUE THREAD

**Issue by juanluisgv1** [gronda-team/signature-ui-sandbox#11]
When a button is defined like this:

```
<form>
…
<PrimaryButton
  name={'activate'}
  form={'job-edit/form'}
  onClick={this.activateJob}
>
  { "Activate" } ==> this will be transform into a <span …>Activate</span>
</PrimaryButton>
</form>
```

Where the `onClick(e)` receives a parameter `e` where you can access the form data like `e.target.form.checkValidation()` to validate the form fields.

**Problem**
If you click of "Activate" being that element a `Span`, the `e.target` will contain the `Span` and not the form. While clicking on the border of the button (not the span) you could access correctly the `e.target.form`.

**Comment by juanluisgv1** [comment]
Btw, the problem I assume is located here 
```
render() {
    const { appearance, size, is, color, __focusMonitor, ...restProps } = this.props;
    return (
      <ButtonRoot
        {...restProps}
        {...this.getNodeAttrs()}
        as={is}
        data-sui-type={'button'}
        data-appearance={appearance}
        data-size={size}
        data-color={color}
        data-focus-origin={this.state.focusOrigin}
        ref={this.getButtonRef}
        onClick={this.onClick}
      >
        <ButtonWrapper>{ this.props.children }</ButtonWrapper>
        <ButtonFocusOverlay />
        <ButtonDisabledOverlay />
      </ButtonRoot>
    )
  }
}
```

**Comment by cesarcosta99** [comment]
We can use `e.currentTarget.form.checkValidation()` and it'll work because the `currentTarget` accesses the target that trigger the event (button) and not the actual target (span).

**Comment by juanluisgv1** [comment]
True @cesarcosta99. I just check the MSD docs https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

> The currentTarget read-only property of the Event interface identifies the current target for the event, as the event traverses the DOM. It always refers to the element to which the event handler has been attached, as opposed to Event.target, which identifies the element on which the event occurred and which may be its direct descendent.

So it's not a SUI issue, but webapp problem.
