### ISSUE TITLE
Checkbox has overflowing text 

### ISSUE THREAD

**Issue by juanluisgv1** [gronda-team/signature-ui-sandbox#5]
Maybe it could be solved by placing `white-space: nowrap` somewhere. 
Make sure that the checkbox text can properly wrap while also ensuring the checkbox is not centered if they're multiline. Use this solution: https://stackoverflow.com/questions/32118013/align-icon-vertically-to-the-center-of-the-first-line-of-text)

**Comment by rayroman** [comment]
Solved sometime ago. Thanks!
