### ISSUE TITLE
Reduce space for form-fields

### ISSUE THREAD

**Issue by juanluisgv1** [gronda-team/signature-ui-sandbox#8]
Decrease space for the form-field margin-bottom and padding-bottom (found in `form-field/styles/theme.js` folders). Please do not adjust the base `lineHeight` that's in the typography file. Instead, try some decimal multipliers to get the space a bit lower. check to see if it looks good in storybook.

**Comment by cesarcosta99** [comment]
As discussed with @juanluisgv1 we decided not to move on with this UI change since the `FormField`s need that space to show an error/hint message that could not be visible but the space need to be there for it.
